apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: jenkins-casc-pipeline
    namespace: jenkins
    files:
      - casc.yaml
      - pipeline.groovy
    options:
      labels:
        jenkins-jenkins-config: "true"
      disableNameSuffixHash: true
