apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-casc-pipeline
  namespace: jenkins
  labels:
    jenkins-jenkins-config: "true"
data:
  pipeline.yaml: |
    jobs:
      - script: >
          pipelineJob('app-pipeline') {
            definition {
              cpsScm {
                scm {
                  git {
                    remote {
                      url('https://github.com/leomerl/full-devops-k8s-iac-solution.git')
                    }
                    branch('app')
                  }
                }
                scriptPath('Jenkinsfile')
              }
            }
          }
