apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argocd
  namespace: flux-system
spec:
  interval: 1h
  targetNamespace: argocd
  chart:
    spec:
      chart: argo-cd
      version: ">=7.0.0 <8.0.0"
      sourceRef:
        kind: HelmRepository
        name: argo
        namespace: flux-system
  install:
    createNamespace: true
  values:
    configs:
      cm:
        users.anonymous.enabled: "true"
      rbac:
        policy.default: role:readonly
    server:
      insecure: true
      service:
        type: NodePort
        nodePortHttp: 32001
